🐛 added checking multisig address before rewriting #LSC-168
lidofinance/terra-multisig-helper pull request #6
Opened 2021-11-12 10:09 UTC by callmepak

2021-11-12 11:28 UTC, pr0n00gler requested changes

2021-11-12 11:28 UTC, pr0n00gler commented on multisig-helper.py
> +        # exit(1)
Why is this line commented out? This change breaks the script a little bit

2021-11-12 11:28 UTC, pr0n00gler commented on multisig-helper.py
> +        print("multisig address is not equal!")
More clearer message about what happened? Something like "your locally generated multisig address is not equal to the one in the Google Sheets".

2021-11-12 11:28 UTC, pr0n00gler commented on multisig-helper.py
> +    if not result["values"][0][0]:
The script fails on this line when a multisig address cell in Google Sheets is empty:
`KeyError: 'values'`

2021-11-12 12:40 UTC, pr0n00gler approved these changes

2021-11-15 12:35 UTC, oopcode commented on multisig-helper.py
> +    if result.get("values") is None:
`if not result.get("values")` is more idiomatic

2021-11-16 09:51 UTC, merged